{{- if .Values.postgresql.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "todochatbot.fullname" . }}-{{ .Values.postgresql.name }}
  labels:
    {{- include "todochatbot.labels" . | nindent 4 }}
    app.kubernetes.io/component: database
spec:
  type: {{ .Values.postgresql.service.type }}
  ports:
    - port: {{ .Values.postgresql.service.port }}
      targetPort: postgres
      protocol: TCP
      name: postgres
  selector:
    {{- include "todochatbot.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: database
{{- end }}
