apiVersion: v2
name: todochatbot
description: A Helm chart for TodoChatBot full-stack application (Frontend + Backend + PostgreSQL)
type: application

version: 0.2.0
appVersion: "1.0.0"

keywords:
  - todo
  - chatbot
  - fastapi
  - nextjs
  - postgresql

maintainers:
  - name: Developer
    email: dev@example.com
